# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrchestraMcp < Formula
  desc "AI-powered project management via Model Context Protocol"
  homepage "https://github.com/orchestra-mcp/mcp"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orchestra-mcp/mcp/releases/download/v0.1.0/orchestra-mcp_darwin_amd64.tar.gz"
      sha256 "6ede06e3663ea72bff44956abeda99211300cf337251bf15cd2df24c974d9654"

      def install
        bin.install "orchestra-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orchestra-mcp/mcp/releases/download/v0.1.0/orchestra-mcp_darwin_arm64.tar.gz"
      sha256 "2b30506cbabc4f3848ebe4b29c3469a8c2a82be57fd544717364d2bb7ab20e8f"

      def install
        bin.install "orchestra-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchestra-mcp/mcp/releases/download/v0.1.0/orchestra-mcp_linux_amd64.tar.gz"
      sha256 "634717d3300fc7fda0011d90b1df1478607352996165e9aef37aa526d01c579d"
      def install
        bin.install "orchestra-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchestra-mcp/mcp/releases/download/v0.1.0/orchestra-mcp_linux_arm64.tar.gz"
      sha256 "dd0bc47f644a82e68a9841e5dd58be70337350d6abd351523a80444690c729e1"
      def install
        bin.install "orchestra-mcp"
      end
    end
  end
end
